name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger on push to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Configure Git identity
        run: |
          git config --global user.name "HatimmD"
          git config --global user.email "hdaanoun2014@gmail.com"

      - name: Set up GitHub authentication
        run: git config --global credential.helper 'cache --timeout=3600'  # Cache credentials for 1 hour

      - name: Install dependencies
        run: npm install

      - name: Deploy to GitHub Pages
        run: npm run deploy
        env:
          API_KEY: ${{ secrets.SECRET_CI }}  # Use the updated secret API_KEY securely
          PFA_HATIM: ${{ secrets.SECRET_PFA }}  # Use the updated secret PFA_HATIM securely
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Use GitHub token for authentication
